version: "3.9"
services:
  mariadb:
    image: mariadb
    volumes:
      - /home/aniskhach/keycloak-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    networks:
        - backend        
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      MYSQL_DATABASE: password
      DB_ADDR: mariadb
      DB_USER: root
      DB_PASSWORD: keycloak
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - "8080:8080"
    networks:
        - backend
        - default        
    depends_on:
      - mariadb
networks:
  default: 
  backend: 
    